language: php
dist: trusty

php:
- 7.2
- 7.3
- 7.4
- nightly

matrix:
    fast_finish: true
    allow_failures:
    - php: nightly

sudo: false

cache:
    directories:
    - $HOME/.composer/cache

install:
- travis_retry composer install --no-interaction --no-suggest

script:
- composer validate --strict
- vendor/bin/phpunit --fail-on-risky
- vendor/bin/phpstan analyse --level 0 src tests